# Generated by Django 5.2 on 2025-04-19 20:01

import script_manager.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ScriptRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "file",
                    models.FileField(
                        upload_to=script_manager.models.upload_to,
                        validators=[script_manager.models.validate_sh_file],
                    ),
                ),
            ],
            options={
                "verbose_name": "Script record",
                "verbose_name_plural": "Script records",
            },
        ),
    ]
