# Generated by Django 5.2 on 2025-04-19 20:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("script_manager", "0001_initial"),
        migrations.swappable_dependency(settings.CONFIG_TEMPLATE_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LabExercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("pending", "Pending"),
                            ("error", "Error"),
                        ],
                        default="inactive",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="LabExerciseDevice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.TextField()),
                (
                    "configuration_status",
                    models.CharField(
                        choices=[
                            ("applied", "Applied"),
                            ("pending", "Pending"),
                            ("error", "Error"),
                        ],
                        default="applied",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "configuration_template",
                    models.ForeignKey(
                        blank=True,
                        help_text="Only applies to OpenWISP devices",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.CONFIG_TEMPLATE_MODEL,
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "lab_exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="devices",
                        to="wifi_lab.labexercise",
                    ),
                ),
                (
                    "script",
                    models.ForeignKey(
                        blank=True,
                        help_text="Only applies to Custom devices",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="script_manager.scriptrecord",
                    ),
                ),
            ],
        ),
    ]
