# Generated by Django 5.2 on 2025-05-09 09:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wifi_lab", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="labexercise",
            name="previous_status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("inactive", "Inactive"),
                    ("pending", "Pending"),
                    ("error", "Error"),
                ],
                default="inactive",
                max_length=10,
            ),
        ),
    ]
