# Generated by Django 5.2 on 2025-04-16 13:24

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("openwisp_users", "0021_rename_user_id_email_openwisp_us_id_06c07a_idx"),
    ]

    operations = [
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "mac_address",
                    models.CharField(
                        max_length=17,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="MAC address must be in the format XX:XX:XX:XX:XX:XX (hexadecimal).",
                                regex="^[0-9A-Fa-f]{2}(:[0-9A-Fa-f]{2}){5}$",
                            )
                        ],
                    ),
                ),
                ("device_key", models.CharField(max_length=32)),
                (
                    "organization",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_devices",
                        to="openwisp_users.organization",
                    ),
                ),
            ],
        ),
    ]
