# Generated by Django 4.2.16 on 2024-12-29 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("openwisp_users", "0020_populate_password_updated_field"),
        ("device_manager", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="organization",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="custom_devices",
                to="openwisp_users.organization",
            ),
        ),
    ]
